# GLM-OCR Feature Objectives
 
## What we want
 
Extract food/ingredient names from a receipt image and map them to canonical ingredient names from the MealDB API. The output is a filtered list of canonical strings that the recipe-matching engine already understands — nothing more. Non-food lines (prices, tax, store name, barcodes) are discarded. The user then confirms which extracted items to add to their pantry.
 
## Architecture decision
 
OCR is the primary path. The pipeline is OCR-first, not GLM-first. Each raw OCR line is the unit of work. It passes through token cleaning, abbreviation expansion, and dictionary matching in sequence before the GLM is ever consulted. The GLM is a fallback for unresolved lines only — it is not a parser and does not write to the pantry directly.
 
## Success criteria
 
- Extracted items are canonical MealDB ingredient names — exact match, no brand phrases or shorthand
- ≥ 80% of returned items resolve to the canonical set before GLM fallback is needed
- ≥ 60% of expected food items on a labeled fixture receipt appear in the output
- Zero non-food strings in the returned list
- Unreadable images and non-receipts return a structured warning, not a 500
## Known extraction problems
 
**Brand names and product branding**
Receipt lines lead with brand names: `QUAKER SQUARES CEREAL`, `KRAFT SHREDDED CHEDDAR`, `HEINZ KETCHUP 32OZ`. The canonical name is the generic food token. Token cleaning strips the brand prefix before matching.
 
**Abbreviated and shorthand lines**
Grocery stores abbreviate to fit column width and there is no standard across chains: `BNLESS CHKN BRST`, `ORG SPNCH 5OZ BAG`, `WHL MLK 1G`. The same ingredient can be abbreviated differently at Walmart vs Kroger vs Publix. The abbreviation expansion table handles known mappings. Fuzzy matching handles novel ones.
 
**Quantity and price tokens on the same line**
Many receipt formats print quantity, unit, and price on the same line as the item name: `2 / $3.49 ROMA TOMATOES`. These are stripped by regex in token cleaning before any matching occurs.
 
**Non-food items**
Receipts include tax lines, subtotals, loyalty points, bag fees, and pharmacy items. These are removed during pre-normalization via pattern matching on known non-food line signatures.
 
**All-caps text**
Most receipt OCR output is all-caps (`OLIVE OIL EV 16OZ`). Lines are normalized to title case before matching to reduce token confusion against MealDB canonical names.
 
**Abbreviation table coverage gaps**
No single lookup table covers all retailers. The table handles high-frequency known mappings. Fuzzy matching handles everything else. The unresolved log is the feedback loop — failed lines are logged and periodically promoted to table entries based on real receipt patterns.
 
---
 
## Pipeline (OCR-first, decided)
 
Pre-normalization and abbreviation expansion happen before any LLM call. GLM fallback is a last resort on null results only.
 
### Order of operations
 
1. **OCR raw line extraction**
   - Each line from the receipt is treated as an independent unit of work
   - OCR provider: Google Cloud Vision (Document AI) for raw text extraction with bounding boxes
   - Lines are returned as an array of raw strings before any processing
2. **Token cleaning**
   - Strip price tokens (`$\d+\.\d+`, unit prices, quantity ratios)
   - Strip weight and unit tokens (`\d+\s*(oz|lb|g|ml|ct|pk|lbs|kg)`)
   - Strip PLU codes (4–5 digit standalone numbers)
   - Strip quantity prefixes (`2 /`, `3x`, leading standalone integers)
   - Strip separator characters (`/ \ | # *`)
   - Normalize all-caps to title case
   - Remove lines matching known non-food patterns (subtotal, tax, total, store name)
3. **Abbreviation expansion**
   - Load `abbreviations.json` once at startup — flat key-value store, generated by LLM seed, grows from unresolved logs
   - Multi-word phrase lookup runs before single-token lookup to preserve compound ingredients (`CHKN BRST → chicken breast` as a unit)
   - Returns the original token lowercased if no match found — downstream steps still receive something workable
   - Table is retailer-agnostic by design — covers patterns seen across receipts processed, not theoretical completeness
4. **Dictionary matching against MealDB**
   - MealDB ingredient list is fetched once and cached locally — no per-line API call
   - Three passes in order: exact string match → fuzzy match via RapidFuzz token sort ratio → embedding similarity as last resort before null
   - Returns the canonical MealDB ingredient name on any pass succeeding
   - Returns null if all three passes fail — triggers GLM fallback
5. **GLM fallback (null results only)**
   - Receives the original raw line plus the cleaned and expanded token as context
   - Prompted to identify the most likely canonical ingredient — not to parse the receipt
   - GLM response re-enters at dictionary matching step, not at the top of the pipeline
   - Never writes to pantry directly — must resolve through MealDB validation to be accepted
   - Unresolved after GLM is logged and returned to the frontend as a review candidate
6. **Unresolved logging**
   - Every null result after GLM fallback is logged with raw line, cleaned token, and expanded token
   - This log is the source for expanding the abbreviation table over time
   - Reflects actual shopping patterns rather than theoretical abbreviation coverage
---
 
## Batch processing and frontend insertion
 
Processing is batch, not streaming. The whole receipt resolves before the frontend receives anything. Total processing time for a typical grocery receipt is 3–6 seconds.
 
- Receipt image is uploaded via `POST /upload/receipt`
- Pipeline runs on each OCR line sequentially, collects all resolved canonical names into an array
- Single JSON response returned to frontend: `extracted_items[]`, `unresolved[]`, `warnings[]`
- Frontend insertion treats resolved items identically to manually typed pantry entries — same dictionary validation, same canonical name, same UI treatment
- `unresolved[]` is surfaced to the user as a review list for optional manual addition
- Manual pantry entry runs through the same dictionary matching layer — fuzzy matching catches typos like `chiken brest` and resolves to `chicken breast` before writing
---
 
## Upload session flow (decided)
 
Session is created server-side at upload time, before OCR results are shown to the user.
 
```
POST /upload/session   → { session_id }   writes: { image_hash, status: pending, uid, created_at }
POST /upload/receipt   → { session_id, raw_text, extracted_items[], unresolved[], warnings[] }
POST /pantry/batch     → confirms selected items, updates session status → confirmed
```
 
- Duplicate image hashes within a time window are rejected before the user waits for OCR
- `session_id` is the lifecycle anchor: `pending → confirmed | discarded | expired`
- Item writes happen only at confirm — no double-write risk
- Pantry items written from a session carry `source: "scan"` and `source_ref: session_id`
---
 
## Abbreviation table management
 
- Seed file generated once via a single LLM call covering common US grocery chain abbreviations
- Stored as `abbreviations.json` — plain file, editable by hand, committed to the repo
- Grows passively: any line that resolves through fuzzy matching or GLM fallback is logged as a candidate pair
- Candidates are auto-promoted when GLM confidence and dictionary match score are both high
- Does not need to be comprehensive before launch — 40–60% first-pass coverage is expected and sufficient given fuzzy matching downstream
---
 
## Bugged upload detection (ship as-is)
 
The server returns a `warnings[]` field on the upload response. The client surfaces these instead of showing an empty list.
 
| Condition | Warning |
|---|---|
| `len(raw_text) < 20` | Unreadable image — could not extract text |
| `len(raw_text) > 200` and `extracted_items = []` | Text found but no ingredients matched |
| `len(extracted_items) > 30` | Unusually long result — possible hallucination |
 
These thresholds are heuristic starting points. Adjust after reviewing real session data.
 
---
 
## Build order
 
The following sequence minimizes over-development and produces a testable result at each step before proceeding.
 
- Dictionary matching against cached MealDB list — validates the truth layer before anything else is built
- Token cleaning — self-contained, testable with hardcoded receipt strings, no external dependencies
- Abbreviation expansion table — seed with LLM call, wire lookup into pipeline after cleaning is confirmed working
- OCR integration — Google Cloud Vision returns raw lines, pipeline already handles the rest
- Batch endpoint — `POST /upload/receipt` wiring OCR output through the pipeline to JSON response
- Frontend receipt upload — file input triggering the endpoint, existing pantry insertion logic handles the response
- GLM fallback — built last, after real receipt failures reveal what actually escapes the main path